In [ ]:
!pip install transformers datasets peft sentence-transformers faiss-cpu accelerate -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.6/23.6 MB 79.4 MB/s eta 0:00:00

In [ ]:
from transformers import GPT2LMHeadModel, GPT2Tokenizer, Trainer, TrainingArguments
from peft import LoraConfig, get_peft_model, PeftModel
from datasets import load_dataset
import torch, os

In [ ]:
# =====================================
# Step 3: Load Dataset
# =====================================
# Your dataset should be in JSON format with keys: "prompt" and "completion"
dataset = load_dataset("json", data_files='clean_healthcare_chatbot_15k_expanded_codemixed.jsonl')['train']
print("Sample example:")
print(dataset[0])

Generating train split: 0 examples [00:00, ? examples/s]

Sample example:
{'prompt': 'Naku stomach pain undi, em cheyyali?', 'completion': 'Stomach pain vunte first light food teesukondi and heavy/spicy/oily food avoid cheyyandi. Warm water or heat pad apply chesi abdominal muscles relax cheyyandi. If vomiting, blood in vomit or severe continuous pain untunte immediate hospital visit avasaram. Mild indigestion ki antacid doctor advice tho teesukovachu but self-medication avoid cheyyandi. Keep hydration and small frequent meals preserve cheyyandi; symptom diary maintain cheyyandi.'}

In [ ]:
# =====================================
# Step 4: Load GPT-2 Small and Apply LoRA (Supports Resuming)
# =====================================
model_name = "gpt2"
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
print("🚀 Starting new training...")
model = GPT2LMHeadModel.from_pretrained(model_name)
lora_config = LoraConfig(
        r=8,
        lora_alpha=32,
        target_modules=["c_attn", "c_proj"],
        lora_dropout=0.1,
        bias="none"
)
model = get_peft_model(model, lora_config)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

🚀 Starting new training...

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/layer.py:2285: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(

In [ ]:
def tokenize(examples):
    # examples is a dict of lists when batched=True
    texts = [p + c for p, c in zip(examples["prompt"], examples["completion"])]
    tokenized = tokenizer(texts, truncation=True, padding="max_length", max_length=128)
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized

tokenized_dataset = dataset.map(tokenize, batched=True)

Map:   0%|          | 0/10500 [00:00<?, ? examples/s]

In [ ]:
!pip install -U transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.11.12)

In [ ]:
training_args = TrainingArguments(
    output_dir="./output",
    per_device_train_batch_size=2,  # T4 friendly
    gradient_accumulation_steps=8,  # effective batch size 16
    learning_rate=2e-4,
    num_train_epochs=30,
    logging_steps=50,
    save_strategy="epoch",
    fp16=True,  # memory-efficient optimizer
    report_to="none"
)
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
)

In [ ]:
trainer.train()
model.save_pretrained("./output")
tokenizer.save_pretrained("./output")

`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

('./output/tokenizer_config.json',
 './output/special_tokens_map.json',
 './output/vocab.json',
 './output/merges.txt',
 './output/added_tokens.json')

In [ ]:
import shutil

shutil.make_archive("output30epochs", 'zip', "output")

'/content/output30epochs.zip'

In [ ]:
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
import json

# 1. Load text KB
with open("kb_docs_rich.txt", "r", encoding="utf-8") as f:
    kb_texts = [line.strip() for line in f if line.strip()]

# 2. Encode using multilingual model
embed_model = SentenceTransformer("l3cube-pune/indic-sentence-bert-nli")
kb_embeddings = embed_model.encode(kb_texts, convert_to_numpy=True, show_progress_bar=True)

# 3. Build FAISS index
dim = kb_embeddings.shape[1]
index = faiss.IndexFlatL2(dim)
index.add(kb_embeddings)

# 4. Save everything
faiss.write_index(index, "faiss_index.index")
with open("kb_texts.json", "w", encoding="utf-8") as f:
    json.dump(kb_texts, f, ensure_ascii=False, indent=2)

print(f"✅ FAISS index built with {len(kb_texts)} entries.")

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/668 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/950M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/577 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/950M [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

✅ FAISS index built with 60 entries.

In [ ]:
import torch, json, faiss
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

# 1️⃣ Correct path to your model folder
model_dir = "/content/output"

# 2️⃣ Load model + tokenizer from Drive
tokenizer = AutoTokenizer.from_pretrained(model_dir)
model = AutoModelForCausalLM.from_pretrained(model_dir, torch_dtype=torch.float16)

# 3️⃣ Create text generation pipeline
generator = pipeline("text-generation", model=model, tokenizer=tokenizer, device_map="auto")

# 4️⃣ Load FAISS index and KB
index = faiss.read_index("/content/faiss_index.index")
with open("/content/kb_texts.json", encoding="utf-8") as f:
    kb_texts = json.load(f)

# 5️⃣ Load sentence embedding model
embed_model = SentenceTransformer("l3cube-pune/indic-sentence-bert-nli")

# 6️⃣ Define retrieval function
def retrieve_top_k(query, k=3):
    query_emb = embed_model.encode([query])
    D, I = index.search(query_emb, k)
    return [kb_texts[i] for i in I[0]]

# 7️⃣ Define RAG response function
def rag_response(user_query):
    context = retrieve_top_k(user_query, k=3)
    prompt = f"### Instruction:\nUser: {user_query}\nContext: {' '.join(context)}\n### Response:\n"
    response = generator(prompt, max_new_tokens=100, temperature=0.7, top_p=0.9)[0]["generated_text"]
    return response.split("### Response:")[-1].strip()

`torch_dtype` is deprecated! Use `dtype` instead!
Device set to use cuda:0

In [ ]:
import json, random

all_data = []
with open("/content/clean_healthcare_chatbot_15k_expanded_codemixed.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if line:  # skip empty lines
            try:
                all_data.append(json.loads(line))
            except json.JSONDecodeError:
                print("Skipping invalid line:", line)

# =====================================
# 3️⃣ Split into train/test
# =====================================
random.seed(42)
random.shuffle(all_data)
test_size = 500  # you can choose 500-1000 for evaluation
test_data = all_data[:test_size]
train_data = all_data[test_size:]

In [ ]:
!pip install evaluate bert_score sacrebleu rouge_score

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting bert_score
  Downloading bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Collecting sacrebleu
  Downloading sacrebleu-2.5.1-py3-none-any.whl.metadata (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.8/51.8 kB 1.7 MB/s eta 0:00:00
Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (25.0)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bert_score) (2.9.0+cu126)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from bert_score) (4.57.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from bert_score) (3.10.0)
Collecting portalocker (from sacrebleu)
  Downloading portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2024.11.6)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (0.9.0)
Collecting colorama (from sacrebleu)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (5.4.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2025.11.12)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.5.0)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score) (0.7.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (3.2.5)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.0.0->bert_score) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.0.0->bert_score) (3.0.3)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 6.5 MB/s eta 0:00:00
Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 7.3 MB/s eta 0:00:00
Downloading sacrebleu-2.5.1-py3-none-any.whl (104 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.1/104.1 kB 10.0 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading portalocker-3.2.0-py3-none-any.whl (22 kB)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=3c12fb53ebbbc0e198ab1a0fd4137bcf722579fbbb6fdcc677dbc30fae107f03
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge_score
Installing collected packages: portalocker, colorama, sacrebleu, rouge_score, evaluate, bert_score
Successfully installed bert_score-0.3.13 colorama-0.4.6 evaluate-0.4.6 portalocker-3.2.0 rouge_score-0.1.2 sacrebleu-2.5.1

In [ ]:
from evaluate import load
bertscore = load("bertscore")

generated_texts = []
reference_texts = []
for entry in test_data:
    user_query = entry["prompt"].split("### Instruction:\n")[-1].split("\n\n### Context:")[0]
    ref = entry["completion"]
    gen = rag_response(user_query)
    generated_texts.append(gen)
    reference_texts.append(ref)

bertscore_results = bertscore.compute(predictions=generated_texts, references=reference_texts, lang="en")
print("BERTScore F1:", sum(bertscore_results["f1"])/len(bertscore_results["f1"]))

Downloading builder script: 0.00B [00:00, ?B/s]

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BERTScore F1: 0.8344425730705262

In [ ]:
from transformers import AutoModelForCausalLM
from tqdm import tqdm # Import tqdm here

model.eval()
def compute_ppl(sentences):
    total_loss = 0.0
    total_tokens = 0
    with torch.no_grad():
        for sent in tqdm(sentences):
            inputs = tokenizer(sent, return_tensors="pt", truncation=True, max_length=128)
            labels = inputs["input_ids"]
            inputs = {k: v.to(model.device) for k, v in inputs.items()} # Move inputs to model device
            outputs = model(**inputs, labels=labels)
            total_loss += outputs.loss.item() * labels.size(1)
            total_tokens += labels.size(1)
    import math
    ppl = math.exp(total_loss / total_tokens)
    return ppl

ppl = compute_ppl(generated_texts)
print("Perplexity on generated responses:", ppl)

100%|██████████| 500/500 [00:20<00:00, 24.93it/s]

Perplexity on generated responses: 119.58883347363532

In [ ]:
from evaluate import load
import numpy as np

# Load metrics
bleu = load("sacrebleu")
rouge = load("rouge")

# Collect generations and references
generated_texts = []
reference_texts = []

for entry in test_data:
    user_query = entry["prompt"].split("### Instruction:\n")[-1].split("\n\n### Context:")[0]
    ref = entry["completion"]
    gen = rag_response(user_query)
    generated_texts.append(gen)
    reference_texts.append(ref)

# -------------------------------
# 1️⃣ BLEU
# -------------------------------
bleu_results = bleu.compute(predictions=generated_texts, references=[[r] for r in reference_texts])
bleu_score = bleu_results["score"]

# -------------------------------
# 2️⃣ ROUGE-L
# -------------------------------
rouge_results = rouge.compute(predictions=generated_texts, references=reference_texts)
rouge_l = rouge_results["rougeL"]

# -------------------------------
# 📊 Print Summary
# -------------------------------
print("\n===== Evaluation Summary =====")
print(f"BLEU: {bleu_score:.2f}")
print(f"ROUGE-L: {rouge_l:.3f}")

# Optionally save to file
with open("bleu_rouge_results.txt", "w") as f:
    f.write(f"BLEU: {bleu_score:.2f}\n")
    f.write(f"ROUGE-L: {rouge_l:.3f}\n")

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

===== Evaluation Summary =====
BLEU: 5.23
ROUGE-L: 0.164

In [ ]:
from sentence_transformers import SentenceTransformer, util
import numpy as np

# Load a multilingual Sentence-BERT model
model = SentenceTransformer('l3cube-pune/indic-sentence-bert-nli')

generated_texts = []
reference_texts = []

# Example: assuming your test_data is already loaded
for entry in test_data:
    user_query = entry["prompt"].split("### Instruction:\n")[-1].split("\n\n### Context:")[0]
    ref = entry["completion"]
    gen = rag_response(user_query)
    generated_texts.append(gen)
    reference_texts.append(ref)

# Compute embeddings
gen_embeds = model.encode(generated_texts, convert_to_tensor=True)
ref_embeds = model.encode(reference_texts, convert_to_tensor=True)

# Compute cosine similarity
cosine_scores = util.cos_sim(gen_embeds, ref_embeds)

# Take diagonal (pairwise scores between matching responses)
pairwise_scores = cosine_scores.diag().cpu().numpy()

# Average similarity
mean_similarity = np.mean(pairwise_scores)
print(f"Average Semantic Similarity: {mean_similarity:.4f}")

Average Semantic Similarity: 0.6092

In [ ]:
queries = [
    "Naku headache vachindi, em cheyyali?",
    "Cough valla em chesthavu?",
    "Throat pain ki emi cheyyali?",
    "Cold vachindi, em cheyyali?"
]

for q in queries:
    print(f"\n🧍 User: {q}")
    codemixed = rag_response(q)  # your fine-tuned GPT-2 + RAG outpu
    print(f"🤖 Bot (Code-mixed Telugu): {codemixed}")

🧍 User: Naku headache vachindi, em cheyyali?
🤖 Bot (Code-mixed Telugu): Maintain healthy weight, hydration and rest; examination and tests doctor advise chesaru.

🧍 User: Cough valla em chesthavu?
🤖 Bot (Code-mixed Telugu): Store cold foods and fluids teesukondi; spicy and cold items avoid cheyyandi. If cough continues beyond 7–10 rojulu, medical evaluation recommended under specialist guidance.

🧍 User: Throat pain ki emi cheyyali?
🤖 Bot (Code-mixed Telugu): Rest, gentle stretching and warm bath chala help chestayi. Avoid heavy lifting and sudden movements; maintain healthy weight to reduce headache. If pain continues beyond 7–10 rojulu, medical evaluation recommended under specialist guidance.

🧍 User: Cold vachindi, em cheyyali?
🤖 Bot (Code-mixed Telugu): Sudden confusion, disorientation or rapid decline unte doctor ni immediate ga kalavandi; neurological evaluation important. Medications and cognitive therapies sometimes recommended under specialist guidance.

In [ ]:
import gradio as gr
import faiss, json, numpy as np
from sentence_transformers import SentenceTransformer
from transformers import pipeline, AutoTokenizer, AutoModelForSeq2SeqLM
import torch

# ==========================================
# 🔧 Initialization
# ==========================================
print("🔁 Initializing models...")

# embedding model
embed_model = SentenceTransformer("l3cube-pune/indic-sentence-bert-nli", device="cuda" if torch.cuda.is_available() else "cpu")

# FAISS + KB
index = faiss.read_index("faiss_index.index")
with open("kb_texts.json", "r", encoding="utf-8") as f:
    kb_texts = json.load(f)

# RAG generation model
generator = pipeline(
    "text-generation",
    model="./output",
    tokenizer="./output",
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)

# Translation model
TRANSLATOR_MODEL = "aryaumesh/english-to-telugu"
translator_tokenizer = AutoTokenizer.from_pretrained(TRANSLATOR_MODEL)
translator_model = AutoModelForSeq2SeqLM.from_pretrained(TRANSLATOR_MODEL)

SRC_LANG = "en_XX"
TGT_LANG = "te_IN"
translator_tokenizer.src_lang = SRC_LANG

print("🔥 All models loaded successfully.")


# ==========================================
# 🧠 Retrieval + RAG Generation
# ==========================================
def retrieve_top_k(query, k=3):
    q_emb = embed_model.encode([query]).astype("float32")
    D, I = index.search(q_emb, k)

    # remove -1 and duplicates
    unique_contexts = []
    for i in I[0]:
        if i != -1 and kb_texts[i] not in unique_contexts:
            unique_contexts.append(kb_texts[i])

    return unique_contexts


def translate_to_telugu(text):
    """Translate code-mixed English Telugu → pure Telugu"""
    try:
        encoded = translator_tokenizer(text, return_tensors="pt")
        generated_tokens = translator_model.generate(
            **encoded,
            forced_bos_token_id=translator_tokenizer.lang_code_to_id[TGT_LANG],
            max_length=150,
            num_beams=5,
            early_stopping=True,
            no_repeat_ngram_size=3,
            repetition_penalty=1.2
        )
        return translator_tokenizer.decode(generated_tokens[0], skip_special_tokens=True)
    except:
        return "⚠️ Translation Failed."


def rag_response(user_query, k=3):
    context_list = retrieve_top_k(user_query)
    context = "\n".join(context_list)

    prompt = f"""
### Instruction:
Help the user with a friendly medical suggestion.

### User Query:
{user_query}

### Knowledge:
{context}

### Response:
"""

    result = generator(prompt, max_new_tokens=250, temperature=0.7, top_p=0.9)[0]["generated_text"]
    final_resp = result.replace(prompt, "").strip()

    return final_resp, context_list


# ==========================================
# 💬 Chat Flow
# ==========================================
def chat_function(message, history):
    code_mixed, context_used = rag_response(message)

    # Translate model response
    telugu_translation = translate_to_telugu(code_mixed)

    # Translate retrieved medical reference
    translated_contexts = [translate_to_telugu(c) for c in context_used]

    response = f"""
🗣 **Code-Mixed Response:**
{code_mixed}

🇮🇳 **Pure Telugu Translation:**
{telugu_translation}

---

📌 **Retrieved Medical Reference (English):**
"""

    for c in context_used:
        response += f"• {c[:180]}...\n"

    response += "\n\n📖 **Retrieved Reference (Telugu Translation):**\n"

    for t in translated_contexts:
        response += f"• {t[:180]}...\n"

    return response



# ==========================================
# 🎨 UI Styling
# ==========================================
custom_css = """
#chatbot {height: 600px !important;}
.gradio-container {background-color: #0d1117 !important;}
.message.user {background-color: #1f6feb !important;color: white;border-radius: 14px;padding: 10px;}
.message.bot {background-color: #161b22 !important;color: #e6edf3 !important;border: 1px solid #30363d;border-radius: 14px;padding: 10px;}
textarea {background-color: #161b22 !important;border-radius: 10px;color: white;border:1px solid #30363d;}
button {background:#238636;color:white;border-radius:8px;font-weight:bold;}
button:hover {background:#2ea043;}
"""


# ==========================================
# 🚀 Launch App
# ==========================================
chatbot = gr.ChatInterface(
    fn=chat_function,
    title="🏥 Telugu HealthGPT",
    description="Ask your health question in Telugu, English or mix.\nExample: `Naku headache undi. Em cheyyali?`",
    css=custom_css,
    examples=[
        ["Naku headache undi, em cheyyali?"],
        ["Cold and cough ki home remedies cheppu."],
        ["Fever vachindi 2 days ninchi. Emi cheyyali?"],
    ]
)

chatbot.queue().launch(share=True)

🔁 Initializing models...

`torch_dtype` is deprecated! Use `dtype` instead!
Device set to use cuda:0

tokenizer_config.json: 0.00B [00:00, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/992 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/2.44G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/256 [00:00<?, ?B/s]

🔥 All models loaded successfully.

/usr/local/lib/python3.12/dist-packages/gradio/chat_interface.py:347: UserWarning: The 'tuples' format for chatbot messages is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style 'role' and 'content' keys.
  self.chatbot = Chatbot(

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://c3fd998dd2a2749496.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)